

class ItemAttributeGroups {
    constructor() {
        this.Attribute1 = new String();
        this.Attribute2 = new String();
        this.Attribute3 = new String();
        this.Attribute4 = new String();
        this.Attribute5 = new String();
        this.Attribute6 = new String();
        this.Attribute7 = new String();
        this.Attribute8 = new String();
        this.Attribute9 = new String();
        this.Attribute10 = new String();
        this.Attribute11 = new String();
        this.Attribute12 = new String();
        this.Attribute13 = new String();
        this.Attribute14 = new String();
        this.Attribute15 = new String();
        this.Attribute16 = new String();
        this.Attribute17 = new String();
        this.Attribute18 = new String();
        this.Attribute19 = new String();
        this.Attribute20 = new String();
        this.Attribute21 = new String();
        this.Attribute22 = new String();
        this.Attribute23 = new String();
        this.Attribute24 = new String();
        this.Attribute25 = new String();
        this.Attribute26 = new String();
        this.Attribute27 = new String();
        this.Attribute28 = new String();
        this.Attribute29 = new String();
        this.Attribute30 = new String();
        this.Attribute31 = new String();
        this.Attribute32 = new String();
        this.Attribute33 = new Number();
        this.Attribute34 = new Number();
        this.Attribute35 = new Number();
        this.Attribute36 = new Number();
        this.Attribute37 = new Number();
        this.Attribute38 = new Number();
        this.Attribute39 = new Number();
        this.Attribute40 = new Number();
        this.Attribute41 = new Number();
        this.Attribute42 = new Number();
        this.Attribute43 = new String();
        this.Attribute44 = new String();
        this.Attribute45 = new String();
        this.Attribute46 = new String();
        this.Attribute47 = new String();
        this.Attribute48 = new Number();
        this.Attribute49 = new Number();
        this.Attribute50 = new Number();
        this.Attribute51 = new Number();
        this.Attribute52 = new Number();
        this.Attribute53 = new Number();
        this.Attribute54 = new Number();
        this.Attribute55 = new Number();
        this.Attribute56 = new Number();
        this.Attribute57 = new Number();
        this.Attribute58 = new Number();
        this.Attribute59 = new Number();
        this.Attribute60 = new Number();
        this.Attribute61 = new Number();
        this.Attribute62 = new Number();
        this.Attribute63 = new Number();
        this.Attribute64 = new Number();
    }
    Attribute1;
    Attribute2;
    Attribute3;
    Attribute4;
    Attribute5;
    Attribute6;
    Attribute7;
    Attribute8;
    Attribute9;
    Attribute10;
    Attribute11;
    Attribute12;
    Attribute13;
    Attribute14;
    Attribute15;
    Attribute16;
    Attribute17;
    Attribute18;
    Attribute19;
    Attribute20;
    Attribute21;
    Attribute22;
    Attribute23;
    Attribute24;
    Attribute25;
    Attribute26;
    Attribute27;
    Attribute28;
    Attribute29;
    Attribute30;
    Attribute31;
    Attribute32;
    Attribute33;
    Attribute34;
    Attribute35;
    Attribute36;
    Attribute37;
    Attribute38;
    Attribute39;
    Attribute40;
    Attribute41;
    Attribute42;
    Attribute43;
    Attribute44;
    Attribute45;
    Attribute46;
    Attribute47;
    Attribute48;
    Attribute49;
    Attribute50;
    Attribute51;
    Attribute52;
    Attribute53;
    Attribute54;
    Attribute55;
    Attribute56;
    Attribute57;
    Attribute58;
    Attribute59;
    Attribute60;
    Attribute61;
    Attribute62;
    Attribute63;
    Attribute64;
}

module.exports = ItemAttributeGroups;