

class TaxExtension {
    constructor() {
        this.TaxId0 = new String();
        this.TaxId1 = new String();
        this.TaxId2 = new String();
        this.TaxId3 = new String();
        this.TaxId4 = new String();
        this.TaxId5 = new String();
        this.TaxId6 = new String();
        this.TaxId7 = new String();
        this.TaxId8 = new String();
        this.TaxId9 = new String();
        this.State = new String();
        this.County = new String();
        this.Incoterms = new String();
        this.Vehicle = new String();
        this.VehicleState = new String();
        this.NFRef = new String();
        this.Carrier = new String();
        this.PackQuantity = new Number();
        this.PackDescription = new String();
        this.Brand = new String();
        this.ShipUnitNo = new Number();
        this.NetWeight = new Number();
        this.GrossWeight = new Number();
        this.StreetS = new String();
        this.BlockS = new String();
        this.BuildingS = new String();
        this.CityS = new String();
        this.ZipCodeS = new String();
        this.CountyS = new String();
        this.StateS = new String();
        this.CountryS = new String();
        this.StreetB = new String();
        this.BlockB = new String();
        this.BuildingB = new String();
        this.CityB = new String();
        this.ZipCodeB = new String();
        this.CountyB = new String();
        this.StateB = new String();
        this.CountryB = new String();
        this.ImportOrExport = new String();
        this.MainUsage = new Number();
        this.GlobalLocationNumberS = new String();
        this.GlobalLocationNumberB = new String();
        this.TaxId12 = new String();
        this.TaxId13 = new String();
        this.BillOfEntryNo = new String();
        this.BillOfEntryDate = new String();
        this.OriginalBillOfEntryNo = new String();
        this.OriginalBillOfEntryDate = new String();
        this.ImportOrExportType = new String();
        this.PortCode = new String();
        this.DocEntry = new Number();
    }
    TaxId0;
    TaxId1;
    TaxId2;
    TaxId3;
    TaxId4;
    TaxId5;
    TaxId6;
    TaxId7;
    TaxId8;
    TaxId9;
    State;
    County;
    Incoterms;
    Vehicle;
    VehicleState;
    NFRef;
    Carrier;
    PackQuantity;
    PackDescription;
    Brand;
    ShipUnitNo;
    NetWeight;
    GrossWeight;
    StreetS;
    BlockS;
    BuildingS;
    CityS;
    ZipCodeS;
    CountyS;
    StateS;
    CountryS;
    StreetB;
    BlockB;
    BuildingB;
    CityB;
    ZipCodeB;
    CountyB;
    StateB;
    CountryB;
    ImportOrExport;
    MainUsage;
    GlobalLocationNumberS;
    GlobalLocationNumberB;
    TaxId12;
    TaxId13;
    BillOfEntryNo;
    BillOfEntryDate;
    OriginalBillOfEntryNo;
    OriginalBillOfEntryDate;
    ImportOrExportType;
    PortCode;
    DocEntry;
}

module.exports = TaxExtension;